<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="292775" started-at="2020-01-05T17:26:15Z" finished-at="2020-01-05T17:31:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="292775" started-at="2020-01-05T17:26:15Z" finished-at="2020-01-05T17:31:08Z">
      <class name="testng.First">
        <test-method status="PASS" signature="startTime()[pri:0, instance:testng.First@6f7fd0e6]" name="startTime" is-config="true" duration-ms="40" started-at="2020-01-05T22:56:15Z" finished-at="2020-01-05T22:56:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTime -->
        <test-method status="FAIL" signature="tc1()[pri:0, instance:testng.First@6f7fd0e6]" name="tc1" duration-ms="40160" started-at="2020-01-05T22:56:15Z" finished-at="2020-01-05T22:56:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [ahmedshabeer1996@gmail.co] but found [ahmedshabeer1996@gmail.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [ahmedshabeer1996@gmail.co] but found [ahmedshabeer1996@gmail.com]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testng.First.tc1(First.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="startTime()[pri:0, instance:testng.First@6f7fd0e6]" name="startTime" is-config="true" duration-ms="0" started-at="2020-01-05T22:56:15Z" finished-at="2020-01-05T22:56:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTime -->
        <test-method status="PASS" signature="startTime()[pri:0, instance:testng.First@6f7fd0e6]" name="startTime" is-config="true" duration-ms="0" started-at="2020-01-05T22:56:56Z" finished-at="2020-01-05T22:56:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTime -->
        <test-method status="PASS" signature="tc2()[pri:0, instance:testng.First@6f7fd0e6]" name="tc2" duration-ms="77000" started-at="2020-01-05T22:56:56Z" finished-at="2020-01-05T22:58:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="endTime()[pri:0, instance:testng.First@6f7fd0e6]" name="endTime" is-config="true" duration-ms="0" started-at="2020-01-05T22:56:56Z" finished-at="2020-01-05T22:56:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTime -->
        <test-method status="PASS" signature="endTime()[pri:0, instance:testng.First@6f7fd0e6]" name="endTime" is-config="true" duration-ms="4" started-at="2020-01-05T22:58:13Z" finished-at="2020-01-05T22:58:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTime -->
        <test-method status="PASS" signature="startTime()[pri:0, instance:testng.First@6f7fd0e6]" name="startTime" is-config="true" duration-ms="2" started-at="2020-01-05T22:58:13Z" finished-at="2020-01-05T22:58:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTime -->
        <test-method status="FAIL" signature="tc3()[pri:0, instance:testng.First@6f7fd0e6]" name="tc3" duration-ms="174428" started-at="2020-01-05T22:58:13Z" finished-at="2020-01-05T23:01:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false],
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false],
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testng.First.tc3(First.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:testng.First@6f7fd0e6]" name="quit" is-config="true" duration-ms="944" started-at="2020-01-05T23:01:07Z" finished-at="2020-01-05T23:01:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="endTime()[pri:0, instance:testng.First@6f7fd0e6]" name="endTime" is-config="true" duration-ms="0" started-at="2020-01-05T23:01:07Z" finished-at="2020-01-05T23:01:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTime -->
      </class> <!-- testng.First -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
